import type { Metadata } from "next";

import "./globals.css";
import Provider from "../state/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div className="app-wrapper">{children}</div>
        </Provider>
      </body>
    </html>
  );
}
